### ISSUE TITLE
“点击下载” is not working after clicking

### ISSUE THREAD

**Issue by li-yuening** [luffyZh/generate-effective-desktop#1]
Button only works for the first time. Thus, if you wanna change sth. a little bit, it's a pain to edit texts and colors again after refreshing the whole page.

**Comment by li-yuening** [comment]
<img width="559" alt="QQ20190919-104703@2x" src="https://user-images.githubusercontent.com/12383502/65209474-d9923f00-daca-11e9-8d48-03dd31c84a77.png">

**Comment by luffyZh** [comment]
@Basign 我这边下载没有任何问题。。。不知道你那边为什么？你试试github page那个链接能下载吗？我这边本地代码和github page的代码一模一样
